function createQuiz(words) {
    const quizContainer = document.querySelector('.quiz');
    let score = 0;
    const selectedWords = words.sort(() => 0.5 - Math.random()).slice(0, 100);

    selectedWords.forEach(word => {
        const question = document.createElement('div');
        question.className = 'quiz-question';
        question.innerHTML = `<p>What is the translation of "${word.english}"?</p>`;
        const options = document.createElement('ul');
        options.className = 'options';

        const correctOption = document.createElement('li');
        correctOption.innerText = word.french;
        correctOption.addEventListener('click', () => {
            correctOption.classList.add('correct');
            score++;
            updateScore(score);
            showExampleSentence(word.example, question);
            storeAnswer(word.english, word.french, true);
        });

        const incorrectOptions = words.filter(w => w !== word).sort(() => 0.5 - Math.random()).slice(0, 3).map(w => {
            const option = document.createElement('li');
            option.innerText = w.french;
            option.addEventListener('click', () => {
                option.classList.add('incorrect');
                updateScore(score);
                showExampleSentence(word.example, question);
                storeAnswer(word.english, option.innerText, false);
            });
            return option;
        });

        const allOptions = [correctOption, ...incorrectOptions].sort(() => 0.5 - Math.random());
        allOptions.forEach(option => options.appendChild(option));

        question.appendChild(options);
        quizContainer.appendChild(question);
    });

    const scoreDisplay = document.createElement('div');
    scoreDisplay.id = 'score';
    scoreDisplay.innerHTML = `<p>Score: ${score}</p>`;
    quizContainer.appendChild(scoreDisplay);
}

function updateScore(score) {
    const scoreDisplay = document.getElementById('score');
    scoreDisplay.innerHTML = `<p>Score: ${score}</p>`;
}

function showExampleSentence(example, questionElement) {
    let exampleContainer = questionElement.querySelector('.example-sentence');
    if (!exampleContainer) {
        exampleContainer = document.createElement('div');
        exampleContainer.className = 'example-sentence';
        questionElement.appendChild(exampleContainer);
    }
    exampleContainer.innerHTML = `<p>Example: ${example}</p>`;
}

function storeAnswer(question, answer, correct) {
    const reviewSection = document.querySelector('.review');
    const reviewItem = document.createElement('div');
    reviewItem.className = 'review-item';
    reviewItem.innerHTML = `<p>Question: ${question}</p><p>Your Answer: ${answer} - ${correct ? 'Correct' : 'Incorrect'}</p>`;
    reviewSection.appendChild(reviewItem);
}

document.addEventListener('DOMContentLoaded', () => {
    const words = [
        { number: 1, english: 'The', french: 'Le, La, Les', example: 'The cat is on the mat.' },
        { number: 2, english: 'Be', french: 'Être', example: 'To be or not to be.' },
        { number: 3, english: 'And', french: 'Et', example: 'You and I are friends.' },
        { number: 4, english: 'Of', french: 'De', example: 'A cup of tea.' },
        { number: 5, english: 'A', french: 'Un, Une', example: 'A dog is barking.' },
        { number: 6, english: 'In', french: 'Dans', example: 'The book is in the bag.' },
        { number: 7, english: 'To', french: 'À, Pour', example: 'I want to go home.' },
        { number: 8, english: 'Have', french: 'Avoir', example: 'I have a car.' },
        { number: 9, english: 'It', french: 'Il, Elle, Cela', example: 'It is raining.' },
        { number: 10, english: 'I', french: 'Je', example: 'I am happy.' },
        { number: 11, english: 'That', french: 'Que, Qui', example: 'I know that man.' },
        { number: 12, english: 'For', french: 'Pour', example: 'This gift is for you.' },
        { number: 13, english: 'You', french: 'Tu, Vous', example: 'You are welcome.' },
        { number: 14, english: 'He', french: 'Il', example: 'He is my brother.' },
        { number: 15, english: 'With', french: 'Avec', example: 'I will go with you.' },
        { number: 16, english: 'On', french: 'Sur, En', example: 'The book is on the table.' },
        { number: 17, english: 'Do', french: 'Faire', example: 'Do your homework.' },
        { number: 18, english: 'Say', french: 'Dire', example: 'What did you say?' },
        { number: 19, english: 'This', french: 'Ce, Cet, Cette', example: 'This is my house.' },
        { number: 20, english: 'They', french: 'Ils, Elles', example: 'They are playing outside.' },
        { number: 21, english: 'At', french: 'À, Chez', example: 'I am at home.' },
        { number: 22, english: 'But', french: 'Mais', example: 'I like it but it\'s expensive.' },
        { number: 23, english: 'We', french: 'Nous', example: 'We are friends.' },
        { number: 24, english: 'His', french: 'Son, Sa', example: 'This is his book.' },
        { number: 25, english: 'From', french: 'De, Depuis', example: 'I am from France.' },
        { number: 26, english: 'Not', french: 'Ne, Pas', example: 'I am not sure.' },
        { number: 27, english: 'By', french: 'Par', example: 'The book is by the window.' },
        { number: 28, english: 'She', french: 'Elle', example: 'She is my sister.' },
        { number: 29, english: 'Or', french: 'Ou', example: 'Tea or coffee?' },
        { number: 30, english: 'As', french: 'Comme', example: 'He works as a teacher.' },
        { number: 31, english: 'What', french: 'Quoi, Quel, Quelle', example: 'What is your name?' },
        { number: 32, english: 'Go', french: 'Aller', example: 'I need to go now.' },
        { number: 33, english: 'Their', french: 'Leur, Leurs', example: 'This is their house.' },
        { number: 34, english: 'Can', french: 'Pouvoir', example: 'Can you help me?' },
        { number: 35, english: 'Who', french: 'Qui', example: 'Who is that?' },
        { number: 36, english: 'Get', french: 'Obtenir, Avoir', example: 'Can you get me a glass of water?' },
        { number: 37, english: 'If', french: 'Si', example: 'If it rains, we will stay inside.' },
        { number: 38, english: 'Would', french: 'Voudrais', example: 'I would like a coffee.' },
        { number: 39, english: 'Her', french: 'Elle', example: 'This is her bag.' },
        { number: 40, english: 'All', french: 'Tout, Toute, Tous', example: 'All people are equal.' },
        { number: 41, english: 'My', french: 'Mon, Ma', example: 'My name is John.' },
        { number: 42, english: 'Make', french: 'Faire, Fabriquer', example: 'I will make dinner.' },
        { number: 43, english: 'About', french: 'À propos de', example: 'Tell me about your day.' },
        { number: 44, english: 'Know', french: 'Savoir', example: 'Do you know the answer?' },
        { number: 45, english: 'Will', french: 'Aller, Vouloir', example: 'I will call you later.' },
        { number: 46, english: 'Up', french: 'En haut, Monter', example: 'He went up the stairs.' },
        { number: 47, english: 'One', french: 'Un, Une', example: 'One apple a day keeps the doctor away.' },
        { number: 48, english: 'Time', french: 'Temps', example: 'What time is it?' },
        { number: 49, english: 'Has', french: 'A', example: 'She has a cat.' },
        { number: 50, english: 'Been', french: 'Été', example: 'He has been to Paris.' },
        { number: 51, english: 'There', french: 'Là, Il y a', example: 'There is a book on the table.' },
        { number: 52, english: 'Year', french: 'Année', example: 'This is the best year ever.' },
        { number: 53, english: 'So', french: 'Donc, Ainsi', example: 'I am so tired.' },
        { number: 54, english: 'Think', french: 'Penser', example: 'What do you think?' },
        { number: 55, english: 'When', french: 'Quand', example: 'When will you arrive?' },
        { number: 56, english: 'Which', french: 'Quel, Quelle', example: 'Which one do you prefer?' },
        { number: 57, english: 'Take', french: 'Prendre', example: 'Take a seat.' },
        { number: 58, english: 'People', french: 'Personnes', example: 'There are many people here.' },
        { number: 59, english: 'Into', french: 'Dans, En', example: 'He went into the house.' },
        { number: 60, english: 'Just', french: 'Juste', example: 'I just arrived.' },
        { number: 61, english: 'See', french: 'Voir', example: 'Can you see the stars?' },
        { number: 62, english: 'Him', french: 'Lui', example: 'I saw him yesterday.' },
        { number: 63, english: 'Your', french: 'Ton, Ta, Votre', example: 'Is this your book?' },
        { number: 64, english: 'Come', french: 'Venir', example: 'Come here, please.' },
        { number: 65, english: 'Could', french: 'Pourrait', example: 'Could you help me?' },
        { number: 66, english: 'Now', french: 'Maintenant', example: 'I am busy right now.' },
        { number: 67, english: 'Than', french: 'Que', example: 'She is taller than him.' },
        { number: 68, english: 'Like', french: 'Comme, Aimer', example: 'I like chocolate.' },
        { number: 69, english: 'Other', french: 'Autre, Autres', example: 'Do you have any other questions?' },
        { number: 70, english: 'How', french: 'Comment', example: 'How are you?' },
        { number: 71, english: 'Then', french: 'Alors', example: 'First wash your hands, then eat.' },
        { number: 72, english: 'Its', french: 'Son, Sa', example: 'The dog wagged its tail.' },
        { number: 73, english: 'Our', french: 'Notre, Nos', example: 'This is our home.' },
        { number: 74, english: 'More', french: 'Plus', example: 'I need more time.' },
        { number: 75, english: 'These', french: 'Ces, Cet, Cette', example: 'These are my friends.' },
        { number: 76, english: 'Way', french: 'Chemin, Manière', example: 'This is the way to the park.' },
        { number: 77, english: 'Look', french: 'Regarder', example: 'Look at the sky.' },
        { number: 78, english: 'First', french: 'Premier, Première', example: 'She was the first to arrive.' },
        { number: 79, english: 'Also', french: 'Aussi', example: 'I also like reading.' },
        { number: 80, english: 'New', french: 'Nouveau, Nouvelle', example: 'This is my new phone.' },
        { number: 81, english: 'Because', french: 'Parce que', example: 'I am late because of traffic.' },
        { number: 82, english: 'Day', french: 'Jour', example: 'Today is a sunny day.' },
        { number: 83, english: 'Use', french: 'Utiliser', example: 'Can I use your phone?' },
        { number: 84, english: 'No', french: 'Non', example: 'No, I don\'t want any.' },
        { number: 85, english: 'Man', french: 'Homme', example: 'He is a tall man.' },
        { number: 86, english: 'Find', french: 'Trouver', example: 'Can you find my keys?' },
        { number: 87, english: 'Here', french: 'Ici', example: 'Come here, please.' },
        { number: 88, english: 'Thing', french: 'Chose', example: 'What is that thing?' },
        { number: 89, english: 'Give', french: 'Donner', example: 'Give me the book.' },
        { number: 90, english: 'Many', french: 'Beaucoup', example: 'Many people are here.' },
        { number: 91, english: 'Well', french: 'Bien', example: 'She speaks well.' },
        { number: 92, english: 'Only', french: 'Seulement', example: 'I only need one.' },
        { number: 93, english: 'Those', french: 'Ceux, Celles', example: 'Those are my shoes.' },
        { number: 94, english: 'Tell', french: 'Dire, Raconter', example: 'Can you tell me a story?' },
        { number: 95, english: 'Very', french: 'Très', example: 'I am very happy.' },
        { number: 96, english: 'Even', french: 'Même, Aussi', example: 'Even he knows that.' },
        { number: 97, english: 'Back', french: 'Arrière', example: 'I will be back soon.' },
        { number: 98, english: 'Any', french: 'N\'importe quel, -le', example: 'Do you have any money?' },
        { number: 99, english: 'Good', french: 'Bon, Bien', example: 'This is a good idea.' },
        { number: 100, english: 'Woman', french: 'Femme', example: 'She is a smart woman.' },
        { number: 101, english: 'Through', french: 'À travers', example: 'We walked through the park.' },
        { number: 102, english: 'Us', french: 'Nous', example: 'This is for us.' },
        { number: 103, english: 'Life', french: 'Vie', example: 'Life is beautiful.' },
        { number: 104, english: 'Child', french: 'Enfant', example: 'The child is playing.' },
        { number: 105, english: 'Work', french: 'Travail', example: 'I have to work today.' },
        { number: 106, english: 'Down', french: 'En bas, Descendre', example: 'She went down the stairs.' },
        { number: 107, english: 'May', french: 'Peut, Mois', example: 'May I help you?' },
        { number: 108, english: 'After', french: 'Après', example: 'Let\'s meet after lunch.' },
        { number: 109, english: 'Should', french: 'Devrait', example: 'You should see this movie.' },
        { number: 110, english: 'Call', french: 'Appeler', example: 'Can you call me?' },
        { number: 111, english: 'World', french: 'Monde', example: 'The world is round.' },
        { number: 112, english: 'Over', french: 'Sur, Au-dessus', example: 'The plane flew over the city.' },
        { number: 113, english: 'School', french: 'École', example: 'I am going to school.' },
        { number: 114, english: 'Still', french: 'Encore', example: 'Are you still here?' },
        { number: 115, english: 'Try', french: 'Essayer', example: 'Try to do your best.' },
        { number: 116, english: 'Last', french: 'Dernier, Dernière', example: 'This is the last one.' },
        { number: 117, english: 'Need', french: 'Besoin', example: 'I need some help.' },
        { number: 118, english: 'Too', french: 'Trop', example: 'This is too heavy.' },
        { number: 119, english: 'Feel', french: 'Sentir', example: 'How do you feel?' },
        { number: 120, english: 'State', french: 'État', example: 'He is in a bad state.' },
        { number: 121, english: 'Never', french: 'Jamais', example: 'I have never been there.' },
        { number: 122, english: 'Why', french: 'Pourquoi', example: 'Why are you late?' },
        { number: 123, english: 'Something', french: 'Quelque chose', example: 'I need something to drink.' },
        { number: 124, english: 'Most', french: 'Le plus', example: 'She is the most talented.' },
        { number: 125, english: 'Much', french: 'Beaucoup', example: 'I don\'t have much time.' },
        { number: 126, english: 'Out', french: 'Dehors', example: 'Let\'s go out.' },
        { number: 127, english: 'Does', french: 'Fait', example: 'Does he know?' },
        { number: 128, english: 'Great', french: 'Grand, Excellent', example: 'This is a great idea.' },
        { number: 129, english: 'Made', french: 'Fait', example: 'This is made of wood.' },
        { number: 130, english: 'Since', french: 'Depuis', example: 'I haven\'t seen him since Monday.' },
        { number: 131, english: 'High', french: 'Haut, Élevé', example: 'The mountain is high.' },
        { number: 132, english: 'Set', french: 'Ensemble, Définir', example: 'Set the table, please.' },
        { number: 133, english: 'Seem', french: 'Sembler', example: 'You seem tired.' },
        { number: 134, english: 'Found', french: 'Trouvé', example: 'I found my keys.' },
        { number: 135, english: 'Might', french: 'Pourrait', example: 'It might rain later.' },
        { number: 136, english: 'Always', french: 'Toujours', example: 'I always wake up early.' },
        { number: 137, english: 'Long', french: 'Long, Longue', example: 'The road is long.' },
        { number: 138, english: 'Own', french: 'Propre', example: 'I have my own car.' },
        { number: 139, english: 'While', french: 'Tandis que', example: 'Wait here while I go inside.' },
        { number: 140, english: 'Before', french: 'Avant', example: 'I will call you before I leave.' },
        { number: 141, english: 'Must', french: 'Doit', example: 'You must see this.' },
        { number: 142, english: 'Home', french: 'Maison', example: 'I am at home.' },
        { number: 143, english: 'Under', french: 'Sous', example: 'The cat is under the table.' },
        { number: 144, english: 'Business', french: 'Affaires', example: 'He has his own business.' },
        { number: 145, english: 'Service', french: 'Service', example: 'The service was excellent.' },
        { number: 146, english: 'Money', french: 'Argent', example: 'I need some money.' },
        { number: 147, english: 'Same', french: 'Même', example: 'We have the same car.' },
        { number: 148, english: 'Mean', french: 'Signifier', example: 'What do you mean?' },
        { number: 149, english: 'Leave', french: 'Quitter', example: 'I have to leave now.' },
        { number: 150, english: 'Though', french: 'Bien que', example: 'Though it was late, we continued working.' },
        { number: 151, english: 'Less', french: 'Moins', example: 'I have less money than before.' },
        { number: 152, english: 'Day', french: 'Jour', example: 'Today is a good day.' },
        { number: 153, english: 'Could', french: 'Pourrait', example: 'Could you pass the salt?' },
        { number: 154, english: 'Great', french: 'Grand, Excellent', example: 'She did a great job.' },
        { number: 155, english: 'Keep', french: 'Garder', example: 'Keep this secret.' },
        { number: 156, english: 'Try', french: 'Essayer', example: 'Try again.' },
        { number: 157, english: 'Real', french: 'Réel, Vrai', example: 'Is this real?' },
        { number: 158, english: 'Fact', french: 'Fait', example: 'That is a fact.' },
        { number: 159, english: 'Ever', french: 'Jamais', example: 'Have you ever been to Paris?' },
        { number: 160, english: 'Thing', french: 'Chose', example: 'What is that thing?' },
        { number: 161, english: 'Make', french: 'Faire, Fabriquer', example: 'Can you make a cake?' },
        { number: 162, english: 'See', french: 'Voir', example: 'I see what you mean.' },
        { number: 163, english: 'Woman', french: 'Femme', example: 'She is a smart woman.' },
        { number: 164, english: 'Man', french: 'Homme', example: 'He is a strong man.' },
        { number: 165, english: 'Child', french: 'Enfant', example: 'The child is sleeping.' },
        { number: 166, english: 'Would', french: 'Voudrais', example: 'I would like some coffee.' },
        { number: 167, english: 'Latter', french: 'Dernier', example: 'The latter part of the film was interesting.' },
        { number: 168, english: 'Place', french: 'Lieu, Endroit', example: 'This is a nice place.' },
        { number: 169, english: 'Work', french: 'Travail', example: 'I have a lot of work to do.' },
        { number: 170, english: 'Part', french: 'Partie', example: 'This is part of the problem.' },
        { number: 171, english: 'There', french: 'Là, Il y a', example: 'There is a book on the table.' },
        { number: 172, english: 'After', french: 'Après', example: 'Let\'s meet after lunch.' },
        { number: 173, english: 'Point', french: 'Point', example: 'What is your point?' },
        { number: 174, english: 'Turn', french: 'Tourner', example: 'Turn left at the corner.' },
        { number: 175, english: 'Should', french: 'Devrait', example: 'You should go to bed early.' },
        { number: 176, english: 'Cause', french: 'Cause', example: 'What is the cause of this?' },
        { number: 177, english: 'Big', french: 'Grand, Gros', example: 'This is a big problem.' },
        { number: 178, english: 'Such', french: 'Tel, Telle', example: 'I have never seen such a thing.' },
        { number: 179, english: 'Good', french: 'Bon, Bien', example: 'This is a good idea.' },
        { number: 180, english: 'Other', french: 'Autre, Autres', example: 'Do you have any other questions?' },
        { number: 181, english: 'Still', french: 'Encore', example: 'Are you still here?' },
        { number: 182, english: 'These', french: 'Ces, Cet, Cette', example: 'These are my books.' },
        { number: 183, english: 'Give', french: 'Donner', example: 'Give me the book.' },
        { number: 184, english: 'Over', french: 'Sur, Au-dessus', example: 'The plane flew over the city.' },
        { number: 185, english: 'Take', french: 'Prendre', example: 'Take a seat.' },
        { number: 186, english: 'Still', french: 'Encore', example: 'She is still waiting.' },
        { number: 187, english: 'An', french: 'Un, Une', example: 'I saw an elephant.' },
        { number: 188, english: 'Country', french: 'Pays', example: 'France is a beautiful country.' },
        { number: 189, english: 'What', french: 'Quoi, Quel, Quelle', example: 'What is your name?' },
        { number: 190, english: 'There', french: 'Là, Il y a', example: 'There is a problem.' },
        { number: 191, english: 'Like', french: 'Comme, Aimer', example: 'I like ice cream.' },
        { number: 192, english: 'Little', french: 'Petit, Petite', example: 'The little boy is sleeping.' },
        { number: 193, english: 'More', french: 'Plus', example: 'I need more time.' },
        { number: 194, english: 'Then', french: 'Alors', example: 'First wash your hands, then eat.' },
        { number: 195, english: 'Start', french: 'Commencer', example: 'Let\'s start the meeting.' },
        { number: 196, english: 'Might', french: 'Pourrait', example: 'It might rain later.' },
        { number: 197, english: 'How', french: 'Comment', example: 'How are you?' },
        { number: 198, english: 'Who', french: 'Qui', example: 'Who is that?' },
        { number: 199, english: 'Using', french: 'En utilisant', example: 'I am using a new software.' },
        { number: 200, english: 'Long', french: 'Long, Longue', example: 'The road is long.' },
        { number: 201, english: 'Four', french: 'Quatre', example: 'I have four books.' },
        { number: 202, english: 'Water', french: 'Eau', example: 'Water is essential for life.' },
        { number: 203, english: 'Last', french: 'Dernier, Dernière', example: 'This is the last one.' },
        { number: 204, english: 'Feel', french: 'Sentir', example: 'How do you feel?' },
        { number: 205, english: 'Seem', french: 'Sembler', example: 'You seem happy.' },
        { number: 206, english: 'Look', french: 'Regarder', example: 'Look at the sky.' },
        { number: 207, english: 'Why', french: 'Pourquoi', example: 'Why are you late?' },
        { number: 208, english: 'Away', french: 'Loin', example: 'The house is far away.' },
        { number: 209, english: 'Would', french: 'Voudrais', example: 'I would like a coffee.' },
        { number: 210, english: 'Now', french: 'Maintenant', example: 'I am busy right now.' },
        { number: 211, english: 'Find', french: 'Trouver', example: 'Can you find my keys?' },
        { number: 212, english: 'Line', french: 'Ligne', example: 'Draw a straight line.' },
        { number: 213, english: 'One', french: 'Un, Une', example: 'One apple a day keeps the doctor away.' },
        { number: 214, english: 'All', french: 'Tout, Toute, Tous', example: 'All people are equal.' },
        { number: 215, english: 'First', french: 'Premier, Première', example: 'She was the first to arrive.' },
        { number: 216, english: 'Year', french: 'Année', example: 'This is the best year ever.' },
        { number: 217, english: 'Way', french: 'Chemin, Manière', example: 'This is the way to the park.' },
        { number: 218, english: 'Day', french: 'Jour', example: 'Today is a sunny day.' },
        { number: 219, english: 'Make', french: 'Faire, Fabriquer', example: 'I will make dinner.' },
        { number: 220, english: 'Matter', french: 'Importe', example: 'It doesn\'t matter.' },
        { number: 221, english: 'Us', french: 'Nous', example: 'This is for us.' },
        { number: 222, english: 'Could', french: 'Pourrait', example: 'Could you help me?' },
        { number: 223, english: 'Great', french: 'Grand, Excellent', example: 'This is a great idea.' },
        { number: 224, english: 'Think', french: 'Penser', example: 'What do you think?' },
        { number: 225, english: 'Say', french: 'Dire', example: 'What did you say?' },
        { number: 226, english: 'After', french: 'Après', example: 'Let\'s meet after lunch.' },
        { number: 227, english: 'An', french: 'Un, Une', example: 'I saw an elephant.' },
        { number: 228, english: 'Go', french: 'Aller', example: 'I need to go now.' },
        { number: 229, english: 'Well', french: 'Bien', example: 'She speaks well.' },
        { number: 230, english: 'Do', french: 'Faire', example: 'Do your homework.' },
        { number: 231, english: 'Some', french: 'Quelques', example: 'I need some help.' },
        { number: 232, english: 'Our', french: 'Notre, Nos', example: 'This is our home.' },
        { number: 233, english: 'These', french: 'Ces, Cet, Cette', example: 'These are my friends.' },
        { number: 234, english: 'Would', french: 'Voudrais', example: 'I would like some coffee.' },
        { number: 235, english: 'Her', french: 'Elle', example: 'This is her bag.' },
        { number: 236, english: 'Him', french: 'Lui', example: 'I saw him yesterday.' },
        { number: 237, english: 'Every', french: 'Tout, Chaque', example: 'Every person is unique.' },
        { number: 238, english: 'Has', french: 'A', example: 'She has a cat.' },
        { number: 239, english: 'Look', french: 'Regarder', example: 'Look at the sky.' },
        { number: 240, english: 'Two', french: 'Deux', example: 'I have two sisters.' },
        { number: 241, english: 'More', french: 'Plus', example: 'I need more time.' },
        { number: 242, english: 'Least', french: 'Le moins', example: 'This is the least of my worries.' },
        { number: 243, english: 'Less', french: 'Moins', example: 'I have less money than before.' },
        { number: 244, english: 'Said', french: 'Dit', example: 'He said it yesterday.' },
        { number: 245, english: 'Before', french: 'Avant', example: 'I will call you before I leave.' },
        { number: 246, english: 'Those', french: 'Ceux, Celles', example: 'Those are my shoes.' },
        { number: 247, english: 'You', french: 'Tu, Vous', example: 'You are welcome.' },
        { number: 248, english: 'Might', french: 'Pourrait', example: 'It might rain later.' },
        { number: 249, english: 'Such', french: 'Tel, Telle', example: 'I have never seen such a thing.' },
        { number: 250, english: 'Now', french: 'Maintenant', example: 'I am busy right now.' },
        { number: 251, english: 'Even', french: 'Même, Aussi', example: 'Even he knows that.' },
        { number: 252, english: 'Must', french: 'Doit', example: 'You must see this.' },
        { number: 253, english: 'Make', french: 'Faire, Fabriquer', example: 'Can you make a cake?' },
        { number: 254, english: 'Might', french: 'Pourrait', example: 'It might rain later.' },
        { number: 255, english: 'Like', french: 'Comme, Aimer', example: 'I like chocolate.' },
        { number: 256, english: 'U', french: 'Toi', example: 'This is for u.' },
        { number: 257, english: 'Seem', french: 'Sembler', example: 'You seem tired.' },
        { number: 258, english: 'Could', french: 'Pourrait', example: 'Could you pass the salt?' },
        { number: 259, english: 'Big', french: 'Grand, Gros', example: 'This is a big problem.' },
        { number: 260, english: 'Has', french: 'A', example: 'She has a dog.' },
        { number: 261, english: 'Come', french: 'Venir', example: 'Come here, please.' },
        { number: 262, english: 'Should', french: 'Devrait', example: 'You should see this movie.' },
        { number: 263, english: 'Number', french: 'Nombre', example: 'What is your phone number?' },
        { number: 264, english: 'Get', french: 'Obtenir, Avoir', example: 'Can you get me a glass of water?' },
        { number: 265, english: 'My', french: 'Mon, Ma', example: 'My name is John.' },
        { number: 266, english: 'Over', french: 'Sur, Au-dessus', example: 'The plane flew over the city.' },
        { number: 267, english: 'Never', french: 'Jamais', example: 'I have never been there.' },
        { number: 268, english: 'Well', french: 'Bien', example: 'She speaks well.' },
        { number: 269, english: 'Might', french: 'Pourrait', example: 'It might rain later.' },
        { number: 270, english: 'Under', french: 'Sous', example: 'The cat is under the table.' },
        { number: 271, english: 'Last', french: 'Dernier, Dernière', example: 'This is the last one.' },
        { number: 272, english: 'While', french: 'Tandis que', example: 'Wait here while I go inside.' },
        { number: 273, english: 'About', french: 'À propos de', example: 'Tell me about your day.' },
        { number: 274, english: 'Three', french: 'Trois', example: 'I have three apples.' },
        { number: 275, english: 'Would', french: 'Voudrais', example: 'I would like some coffee.' },
        { number: 276, english: 'The', french: 'Le, La, Les', example: 'The cat is on the mat.' },
        { number: 277, english: 'Through', french: 'À travers', example: 'We walked through the park.' },
        { number: 278, english: 'Each', french: 'Chaque', example: 'Each student has a book.' },
        { number: 279, english: 'It', french: 'Il, Elle, Cela', example: 'It is raining.' },
        { number: 280, english: 'Every', french: 'Tout, Chaque', example: 'Every person is unique.' },
        { number: 281, english: 'More', french: 'Plus', example: 'I need more time.' },
        { number: 282, english: 'Most', french: 'Le plus', example: 'She is the most talented.' },
        { number: 283, english: 'Other', french: 'Autre, Autres', example: 'Do you have any other questions?' },
        { number: 284, english: 'Some', french: 'Quelques', example: 'I need some help.' },
        { number: 285, english: 'Much', french: 'Beaucoup', example: 'I don\'t have much time.' },
        { number: 286, english: 'No', french: 'Non', example: 'No, I don\'t want any.' },
        { number: 287, english: 'Any', french: 'N\'importe quel, -le', example: 'Do you have any money?' },
        { number: 288, english: 'Such', french: 'Tel, Telle', example: 'I have never seen such a thing.' },
        { number: 289, english: 'Only', french: 'Seulement', example: 'I only need one.' },
        { number: 290, english: 'Own', french: 'Propre', example: 'I have my own car.' },
        { number: 291, english: 'Such', french: 'Tel, Telle', example: 'I have never seen such a thing.' },
        { number: 292, english: 'Very', french: 'Très', example: 'I am very happy.' },
        { number: 293, english: 'So', french: 'Donc, Ainsi', example: 'I am so tired.' },
        { number: 294, english: 'Their', french: 'Leur, Leurs', example: 'This is their house.' },
        { number: 295, english: 'After', french: 'Après', example: 'Let\'s meet after lunch.' },
        { number: 296, english: 'Few', french: 'Peu', example: 'I have a few friends.' },
        { number: 297, english: 'Having', french: 'Ayant', example: 'Having finished, he left.' },
        { number: 298, english: 'Rather', french: 'Plutôt', example: 'I would rather stay home.' },
        { number: 299, english: 'Very', french: 'Très', example: 'I am very happy.' },
        { number: 300, english: 'Do', french: 'Faire', example: 'Do your homework.' },
        { number: 301, english: 'Its', french: 'Son, Sa', example: 'The dog wagged its tail.' },
        { number: 302, english: 'Very', french: 'Très', example: 'I am very happy.' },
        { number: 303, english: 'Also', french: 'Aussi', example: 'I also like reading.' },
        { number: 304, english: 'Instead', french: 'Au lieu de', example: 'Let\'s walk instead of driving.' },
        { number: 305, english: 'Such', french: 'Tel, Telle', example: 'I have never seen such a thing.' },
        { number: 306, english: 'Up', french: 'En haut, Monter', example: 'He went up the stairs.' },
        { number: 307, english: 'Just', french: 'Juste', example: 'I just arrived.' },
        { number: 308, english: 'What', french: 'Quoi, Quel, Quelle', example: 'What is your name?' },
        { number: 309, english: 'Now', french: 'Maintenant', example: 'I am busy right now.' },
        { number: 310, english: 'Before', french: 'Avant', example: 'I will call you before I leave.' },
        { number: 311, english: 'Though', french: 'Bien que', example: 'Though it was late, we continued working.' },
        { number: 312, english: 'Like', french: 'Comme, Aimer', example: 'I like chocolate.' },
        { number: 313, english: 'Therefore', french: 'Donc, Par conséquent', example: 'It is raining; therefore, we will stay inside.' },
        { number: 314, english: 'However', french: 'Cependant', example: 'It is raining; however, I will go out.' },
        { number: 315, english: 'Too', french: 'Trop', example: 'This is too heavy.' },
        { number: 316, english: 'Can', french: 'Pouvoir', example: 'Can you help me?' },
        { number: 317, english: 'Will', french: 'Aller, Vouloir', example: 'I will call you later.' },
        { number: 318, english: 'Able', french: 'Capable', example: 'I am able to do this.' },
        { number: 319, english: 'About', french: 'À propos de', example: 'Tell me about your day.' },
        { number: 320, english: 'Across', french: 'À travers', example: 'We walked across the bridge.' },
        { number: 321, english: 'After', french: 'Après', example: 'Let\'s meet after lunch.' },
        { number: 322, english: 'All', french: 'Tout, Toute, Tous', example: 'All people are equal.' },
        { number: 323, english: 'Almost', french: 'Presque', example: 'I am almost there.' },
        { number: 324, english: 'Also', french: 'Aussi', example: 'I also like reading.' },
        { number: 325, english: 'Am', french: 'Suis', example: 'I am happy.' },
        { number: 326, english: 'Among', french: 'Parmi', example: 'I am among friends.' },
        { number: 327, english: 'An', french: 'Un, Une', example: 'I saw an elephant.' },
        { number: 328, english: 'And', french: 'Et', example: 'You and I are friends.' },
        { number: 329, english: 'Any', french: 'N\'importe quel, -le', example: 'Do you have any money?' },
        { number: 330, english: 'Are', french: 'Sont', example: 'They are here.' },
        { number: 331, english: 'As', french: 'Comme', example: 'He works as a teacher.' },
        { number: 332, english: 'At', french: 'À, Chez', example: 'I am at home.' },
        { number: 333, english: 'Be', french: 'Être', example: 'To be or not to be.' },
        { number: 334, english: 'Because', french: 'Parce que', example: 'I am late because of traffic.' },
        { number: 335, english: 'Been', french: 'Été', example: 'He has been to Paris.' },
        { number: 336, english: 'But', french: 'Mais', example: 'I like it but it\'s expensive.' },
        { number: 337, english: 'By', french: 'Par', example: 'The book is by the window.' },
        { number: 338, english: 'Can', french: 'Pouvoir', example: 'Can you help me?' },
        { number: 339, english: 'Cannot', french: 'Ne peut pas', example: 'I cannot do this.' },
        { number: 340, english: 'Could', french: 'Pourrait', example: 'Could you help me?' },
        { number: 341, english: 'Day', french: 'Jour', example: 'Today is a sunny day.' },
        { number: 342, english: 'Do', french: 'Faire', example: 'Do your homework.' },
        { number: 343, english: 'Each', french: 'Chaque', example: 'Each student has a book.' },
        { number: 344, english: 'Even', french: 'Même, Aussi', example: 'Even he knows that.' },
        { number: 345, english: 'Find', french: 'Trouver', example: 'Can you find my keys?' },
        { number: 346, english: 'First', french: 'Premier, Première', example: 'She was the first to arrive.' },
        { number: 347, english: 'For', french: 'Pour', example: 'This gift is for you.' },
        { number: 348, english: 'From', french: 'De, Depuis', example: 'I am from France.' },
        { number: 349, english: 'Get', french: 'Obtenir, Avoir', example: 'Can you get me a glass of water?' },
        { number: 350, english: 'Go', french: 'Aller', example: 'I need to go now.' },
        { number: 351, english: 'Good', french: 'Bon, Bien', example: 'This is a good idea.' },
        { number: 352, english: 'Have', french: 'Avoir', example: 'I have a car.' },
        { number: 353, english: 'He', french: 'Il', example: 'He is my brother.' },
        { number: 354, english: 'Her', french: 'Elle', example: 'This is her bag.' },
        { number: 355, english: 'Him', french: 'Lui', example: 'I saw him yesterday.' },
        { number: 356, english: 'His', french: 'Son, Sa', example: 'This is his book.' },
        { number: 357, english: 'How', french: 'Comment', example: 'How are you?' },
        { number: 358, english: 'I', french: 'Je', example: 'I am happy.' },
        { number: 359, english: 'If', french: 'Si', example: 'If it rains, we will stay inside.' },
        { number: 360, english: 'In', french: 'Dans', example: 'The book is in the bag.' },
        { number: 361, english: 'Into', french: 'Dans, En', example: 'He went into the house.' },
        { number: 362, english: 'Is', french: 'Est', example: 'He is here.' },
        { number: 363, english: 'It', french: 'Il, Elle, Cela', example: 'It is raining.' },
        { number: 364, english: 'Its', french: 'Son, Sa', example: 'The dog wagged its tail.' },
        { number: 365, english: 'Just', french: 'Juste', example: 'I just arrived.' },
        { number: 366, english: 'Know', french: 'Savoir', example: 'Do you know the answer?' },
        { number: 367, english: 'Like', french: 'Comme, Aimer', example: 'I like chocolate.' },
        { number: 368, english: 'Make', french: 'Faire, Fabriquer', example: 'I will make dinner.' },
        { number: 369, english: 'Man', french: 'Homme', example: 'He is a tall man.' },
        { number: 370, english: 'Many', french: 'Beaucoup', example: 'Many people are here.' },
        { number: 371, english: 'May', french: 'Peut, Mois', example: 'May I help you?' },
        { number: 372, english: 'Me', french: 'Moi', example: 'Give me the book.' },
        { number: 373, english: 'More', french: 'Plus', example: 'I need more time.' },
        { number: 374, english: 'My', french: 'Mon, Ma', example: 'My name is John.' },
        { number: 375, english: 'No', french: 'Non', example: 'No, I don\'t want any.' },
        { number: 376, english: 'Not', french: 'Ne, Pas', example: 'I am not sure.' },
        { number: 377, english: 'Now', french: 'Maintenant', example: 'I am busy right now.' },
        { number: 378, english: 'Of', french: 'De', example: 'A cup of tea.' },
        { number: 379, english: 'On', french: 'Sur, En', example: 'The book is on the table.' },
        { number: 380, english: 'One', french: 'Un, Une', example: 'One apple a day keeps the doctor away.' },
        { number: 381, english: 'Only', french: 'Seulement', example: 'I only need one.' },
        { number: 382, english: 'Or', french: 'Ou', example: 'Tea or coffee?' },
        { number: 383, english: 'Other', french: 'Autre, Autres', example: 'Do you have any other questions?' },
        { number: 384, english: 'Our', french: 'Notre, Nos', example: 'This is our home.' },
        { number: 385, english: 'Out', french: 'Dehors', example: 'Let\'s go out.' },
        { number: 386, english: 'Said', french: 'Dit', example: 'He said it yesterday.' },
        { number: 387, english: 'See', french: 'Voir', example: 'Can you see the stars?' },
        { number: 388, english: 'She', french: 'Elle', example: 'She is my sister.' },
        { number: 389, english: 'So', french: 'Donc, Ainsi', example: 'I am so tired.' },
        { number: 390, english: 'Some', french: 'Quelques', example: 'I need some help.' },
        { number: 391, english: 'Take', french: 'Prendre', example: 'Take a seat.' },
        { number: 392, english: 'Than', french: 'Que', example: 'She is taller than him.' },
        { number: 393, english: 'That', french: 'Que, Qui', example: 'I know that man.' },
        { number: 394, english: 'The', french: 'Le, La, Les', example: 'The cat is on the mat.' },
        { number: 395, english: 'Their', french: 'Leur, Leurs', example: 'This is their house.' },
        { number: 396, english: 'Them', french: 'Eux, Elles', example: 'I saw them yesterday.' },
        { number: 397, english: 'Then', french: 'Alors', example: 'First wash your hands, then eat.' },
        { number: 398, english: 'There', french: 'Là, Il y a', example: 'There is a book on the table.' },
        { number: 399, english: 'These', french: 'Ces, Cet, Cette', example: 'These are my friends.' },
        { number: 400, english: 'They', french: 'Ils, Elles', example: 'They are playing outside.' },
        { number: 401, english: 'This', french: 'Ce, Cet, Cette', example: 'This is my house.' },
        { number: 402, english: 'Time', french: 'Temps', example: 'What time is it?' },
        { number: 403, english: 'To', french: 'À, Pour', example: 'I want to go home.' },
        { number: 404, english: 'Two', french: 'Deux', example: 'I have two sisters.' },
        { number: 405, english: 'Up', french: 'En haut, Monter', example: 'He went up the stairs.' },
        { number: 406, english: 'Us', french: 'Nous', example: 'This is for us.' },
        { number: 407, english: 'Use', french: 'Utiliser', example: 'Can I use your phone?' },
        { number: 408, english: 'Was', french: 'Était', example: 'He was here.' },
        { number: 409, english: 'We', french: 'Nous', example: 'We are friends.' },
        { number: 410, english: 'What', french: 'Quoi, Quel, Quelle', example: 'What is your name?' },
        { number: 411, english: 'When', french: 'Quand', example: 'When will you arrive?' },
        { number: 412, english: 'Which', french: 'Quel, Quelle', example: 'Which one do you prefer?' },
        { number: 413, english: 'Will', french: 'Aller, Vouloir', example: 'I will call you later.' },
        { number: 414, english: 'With', french: 'Avec', example: 'I will go with you.' },
        { number: 415, english: 'Would', french: 'Voudrais', example: 'I would like a coffee.' },
        { number: 416, english: 'Yes', french: 'Oui', example: 'Yes, please.' },
        { number: 417, english: 'You', french: 'Tu, Vous', example: 'You are welcome.' }
    ];

    createQuiz(words);
});
